### ISSUE TITLE
ZIP upload of GIs not working

### ISSUE THREAD

**Issue by emasters** [CCALI/a2jdocker#2]
Using the upload functionality at `http://localhost:53080/a2j-viewer/viewer/` gives me 2 results:

- A fatal error: `Fatal error: Uncaught Error: Class 'ZipArchive' not found in /var/www/html/a2j-viewer/viewer/index.php:42 Stack trace: #0 {main} thrown in /var/www/html/a2j-viewer/viewer/index.php on line 42`
- Occasionally I see a 404 error after doing an upload.

In neither case do I get a GI listed on the homepage so it seems like the whole upload fails.

**Comment by tobiasnteireho** [comment]
added ZipArchive dependencies. Uploader is now functional in docker.

**Comment by emasters** [comment]
Confirming that uploading of ZIP files is now working.
